# -*- coding: utf-8 -*-
"""Gaussian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9WOlVF4WtaPoO_Bv_n4cd9xpl0i0IBQ
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gaussian_kde

def generate_fuzzed_gaussian(mu, sigma, IN_sigma, k, size):
    IN_mu = k * IN_sigma  # Làm mờ mu dựa theo IN_sigma
    data = []

    for _ in range(size // 2):
        # Fuzz hóa mu và sigma
        fuzzed_mu = np.random.uniform(mu - mu * IN_mu, mu + mu * IN_mu)
        fuzzed_sigma = max(1e-6, np.random.uniform(sigma - sigma * IN_sigma, sigma + sigma * IN_sigma))

        # Sinh 2 biến chuẩn bằng Box-Muller
        u1, u2 = np.random.uniform(0, 1, 2)
        z0 = np.sqrt(-2 * np.log(u1)) * np.cos(2 * np.pi * u2)
        z1 = np.sqrt(-2 * np.log(u1)) * np.sin(2 * np.pi * u2)

        data.append(fuzzed_mu + fuzzed_sigma * z0)
        data.append(fuzzed_mu + fuzzed_sigma * z1)

    return np.array(data[:size])

# Tham số chính
mu, sigma, size = 180, 10, 100000
IN_sigma_levels = [0.0, 0.2, 0.4, 0.6, 0.8]
k = 0.2  # Hệ số fuzz mu dựa trên IN_sigma

# Vẽ biểu đồ KDE
plt.figure(figsize=(12, 8))
x_vals = np.linspace(mu - 5 * sigma, mu + 5 * sigma, 1000)

for IN_sigma in IN_sigma_levels:
    data = generate_fuzzed_gaussian(mu, sigma, IN_sigma, k, size)
    kde = gaussian_kde(data)
    plt.plot(x_vals, kde(x_vals), label=f"IN_sigma={IN_sigma}, IN_mu={k * IN_sigma:.2f}", linewidth=2)

plt.title("KDE Gaussian with Fuzzed Indeterminacy Levels (IN_Mu = 0.2 × IN_sigma)")
plt.xlabel("Value")
plt.ylabel("Density")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis, kstest

# Hàm sinh dữ liệu Gaussian có fuzz mu và sigma
def generate_fuzzed_gaussian(mu, sigma, k, IN_sigma, size):
    IN_mu = k * IN_sigma  # Tỉ lệ fuzz cho mu
    data = []
    for _ in range(size // 2):
        fuzzed_mu = np.random.uniform(mu - mu * IN_mu, mu + mu * IN_mu)
        fuzzed_sigma = max(0.1, np.random.uniform(sigma - sigma * IN_sigma, sigma + sigma * IN_sigma))
        u1, u2 = np.random.uniform(0, 1, 2)
        z0 = np.sqrt(-2 * np.log(u1)) * np.cos(2 * np.pi * u2)
        z1 = np.sqrt(-2 * np.log(u1)) * np.sin(2 * np.pi * u2)
        data.append(fuzzed_mu + fuzzed_sigma * z0)
        data.append(fuzzed_mu + fuzzed_sigma * z1)
    return np.array(data[:size])

# Hàm thống kê mô tả + kiểm định KS
def summarize(data, label, ref_mu, ref_sigma):
    return {
        "type": label,
        "mean": np.mean(data),
        "std": np.std(data),
        "skew": skew(data),
        "kurtosis": kurtosis(data),
        "ks_pvalue": kstest(data, 'norm', args=(ref_mu, ref_sigma)).pvalue
    }

# Tham số đầu vào
mu, sigma, size = 180, 10, 100000
k = 0.2
IN_sigma_levels = [0.0, 0.2, 0.4, 0.6, 0.8]

# Thực hiện sinh và tổng hợp dữ liệu
summary = []
for IN in IN_sigma_levels:
    data = generate_fuzzed_gaussian(mu, sigma, k, IN, size)
    label = f"IN={IN}"
    summary.append(summarize(data, label, mu, sigma))

# In kết quả
df = pd.DataFrame(summary)
print(df.to_string(index=False))

